# Built by packaging/build-rpm.sh inside a Fedora container: the binary is compiled
# first, so this spec only lays out files. Library dependencies are generated by rpm
# from the binary itself.
%global debug_package %{nil}

Name:           pigeon
Version:        %{pigeon_version}
Release:        1%{?dist}
Summary:        Fast, native API client for GNOME
License:        MIT
URL:            https://github.com/optis20052/Pigeon
Source0:        pigeon
Source1:        dev.pigeon.Pigeon.desktop
Source2:        dev.pigeon.Pigeon.svg
Source3:        LICENSE
Source4:        README.md

# the automatic soname dependencies don't carry versions; Pigeon needs these at least
Requires:       gtk4 >= 4.12
Requires:       libadwaita >= 1.7

%description
Pigeon builds, sends and tests HTTP requests. It organizes requests in
projects and collections, supports environments and variables, imports
OpenAPI / Swagger specs and cURL commands, and generates code snippets.
Built with Rust, GTK4 and libadwaita.

%prep
cp %{SOURCE3} %{SOURCE4} .

%install
install -Dm755 %{SOURCE0} %{buildroot}%{_bindir}/pigeon
install -Dm644 %{SOURCE1} %{buildroot}%{_datadir}/applications/dev.pigeon.Pigeon.desktop
install -Dm644 %{SOURCE2} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/dev.pigeon.Pigeon.svg

%files
%license LICENSE
%doc README.md
%{_bindir}/pigeon
%{_datadir}/applications/dev.pigeon.Pigeon.desktop
%{_datadir}/icons/hicolor/scalable/apps/dev.pigeon.Pigeon.svg

%changelog
* Fri Sep 25 2026 Ali <ali@spentys.com> - 0.1.0-1
- First release
